### ISSUE TITLE
格式化带有条件编译的代码时出现异常

### ISSUE THREAD

**Issue by aliang888** [zqy233/formatAndSave#20]
![format-error](https://github.com/zqy233/formatAndSave/assets/19453262/507300ec-72d4-42fb-b818-9e333b9e63bb)

左侧的逗号是在条件编译里面，格式化后，跑到外面了，正然就语法错误了

**Comment by zqy233** [comment]
感谢反馈，已复现，测试该效果同vscode-prettier表现一致，非本插件问题。因为json中条件编译注释是uniapp团队自创的语法，正常json文件不支持注释语法，可以.prettierignore中添加该文件名，忽略该文件格式化，或者前往prettier仓库提问题（uniapp团队自创语法，非规范性语法，可能人家不会修复）
